# google/protobuf/message.pyi
from __future__ import annotations

from typing import Any, Mapping

from custom_components.googlefindmy.protobuf_typing import MessageProto


class Message(MessageProto):
    DESCRIPTOR: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def __getattr__(self, name: str) -> Any: ...

    def __setattr__(self, name: str, value: Any) -> None: ...

    def __delattr__(self, name: str) -> None: ...

    def CopyFrom(self, other: Message) -> None: ...

    def MergeFrom(self, other: Message) -> None: ...

    def SerializePartialToString(self, **kwargs: Any) -> bytes: ...

    def ParseFromString(self, data: bytes) -> None: ...

    def __deepcopy__(self, memo: Mapping[int, object]) -> Message: ...
