# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_components/googlefindmy/ProtoDecoders/RpcStatus.proto
# ruff: noqa: E402, E712, F401, F821 (protoc-generated code uses dynamic globals)
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# Import Any_pb2 to register the google.protobuf.Any type in the descriptor pool
from custom_components.googlefindmy.ProtoDecoders import (
    Any_pb2 as _any_pb2,  # noqa: F401
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n<custom_components/googlefindmy/ProtoDecoders/RpcStatus.proto\x12\ngoogle.rpc\x1a\x36\x63ustom_components/googlefindmy/ProtoDecoders/Any.proto\"N\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Anyb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'custom_components.googlefindmy.ProtoDecoders.RpcStatus_pb2', globals()
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _STATUS._serialized_start = 132
    _STATUS._serialized_end = 210
# @@protoc_insertion_point(module_scope)
